### 변수설정
@deleteUserId = 1


### 1. 관리자가 닉네임,이메일 포함 유저 검색
GET http://localhost:8080/api/admin/search
Content-Type: application/json

{
  "type": "ALL",
  "keyword": "유저1"
}

### 2. 관리자가 닉네임,이메일 포함 유저 검색 2
GET http://localhost:8080/api/admin/search
Content-Type: application/json

{
  "type": "ALL",
  "keyword": "test@test.com"
}

### 3. 관리자가 닉네임으로 유저 검색
GET http://localhost:8080/api/admin/search
Content-Type: application/json

{
  "type": "NICKNAME",
  "keyword": "유저1"
}

### 4. 관리자가 이메일로 유저 검색
GET http://localhost:8080/api/admin/search
Content-Type: application/json

{
  "type": "EMAIL",
  "keyword": "test@test.com"
}

### 5. 관리자가 잘못된 타입으로 유저 검색
GET http://localhost:8080/api/admin/search
Content-Type: application/json

{
  "type": "ANY",
  "keyword": "any"
}

### 6. 관리자가 유저 하드 삭제
DELETE http://localhost:8080/api/admin/{{deleteUserId}}